### ISSUE TITLE
Decidir nova fonte do AraraBots

### ISSUE THREAD

**Issue by Menchik** [Ararabots-UFMS/Ararabots-UFMS.github.io#19]
## Critérios de aprovação
- A fonte precisa ser aprovada por maior parte da equipe

**Comment by rafael-torres-nantes** [comment]
# Fontes
[Site do Google de Fonts](https://fonts.google.com/?preview.text=AraraBots&classification=Monospace) e [Site de Fontes Grátis](https://online-fonts.com/fonts/noto-sans-avestan)

## Mulish

Mulish is a minimalist Sans Serif typeface, designed for both display and text typography.

![Fonte Mulish](https://github.com/Ararabots-UFMS/Ararabots-UFMS.github.io/assets/58231791/fd90b613-855e-45c4-807e-aac8765998fc)

## Arial

![Fonte Arial](https://github.com/Ararabots-UFMS/Ararabots-UFMS.github.io/assets/58231791/d9ac6d83-36ae-419a-8d1c-d21188d7f329)

## Noto Sans Avestan

Noto Sans Mono is a monospaced, unmodulated (“sans serif”) design suitable for programming code and other uses where a fixed-width font is needed. It supports the Latin, Cyrillic and Greek scripts, and various symbols. It has multiple weights and widths, and 3,787 glyphs.



![Noto Sans Avestan](https://github.com/Ararabots-UFMS/Ararabots-UFMS.github.io/assets/58231791/4459f2cf-4f90-4c79-beaf-8774568c651f)
